#pragma once

#define WIN32_LEAN_AND_MEAN             // 从 Windows 头文件中排除极少使用的内容
// Windows 头文件
#include <windows.h>

#pragma comment(lib, "ws2_32.lib")      // Winsock 网络函数
#pragma comment(lib, "shlwapi.lib")     // Shell API (StrRetToStrW)
#pragma comment(lib, "dwrite.lib") 
#pragma comment(lib, "Iphlpapi.lib")
#pragma comment(lib, "dnsapi.lib")
#pragma comment(lib, "Bcrypt.lib")


#include <librsvg-2.0/librsvg/rsvg.h>
#pragma comment(lib, "brotlicommon.lib")
#pragma comment(lib, "brotlidec.lib")
#pragma comment(lib, "brotlienc.lib")
#pragma comment(lib, "bz2.lib")
#pragma comment(lib, "cairo.lib")
#pragma comment(lib, "cairo-gobject.lib")
#pragma comment(lib, "cairo-script-interpreter.lib")
#pragma comment(lib, "charset.lib")
#pragma comment(lib, "croco-0.6.lib")
#pragma comment(lib, "ffi.lib")
#pragma comment(lib, "fontconfig.lib")
#pragma comment(lib, "freetype.lib")
#pragma comment(lib, "fribidi.lib")
#pragma comment(lib, "gdk_pixbuf-2.0.lib")
#pragma comment(lib, "gio-2.0.lib")
#pragma comment(lib, "girepository-2.0.lib")
#pragma comment(lib, "glib-2.0.lib")
#pragma comment(lib, "gmodule-2.0.lib")
#pragma comment(lib, "gobject-2.0.lib")
#pragma comment(lib, "gthread-2.0.lib")
#pragma comment(lib, "harfbuzz.lib")
#pragma comment(lib, "harfbuzz-subset.lib")
#pragma comment(lib, "iconv.lib")
#pragma comment(lib, "intl.lib")
#pragma comment(lib, "jpeg.lib")
#pragma comment(lib, "libexpatMT.lib")
#pragma comment(lib, "libpng16.lib")
#pragma comment(lib, "libxml2.lib")
#pragma comment(lib, "lzma.lib")
#pragma comment(lib, "pango-1.0.lib")
#pragma comment(lib, "pangocairo-1.0.lib")
#pragma comment(lib, "pangoft2-1.0.lib")
#pragma comment(lib, "pangowin32-1.0.lib")
#pragma comment(lib, "pcre2-8.lib")
#pragma comment(lib, "pcre2-16.lib")
#pragma comment(lib, "pcre2-32.lib")
#pragma comment(lib, "pcre2-posix.lib")
#pragma comment(lib, "pixman-1.lib")
#pragma comment(lib, "pthreadVC3.lib")
#pragma comment(lib, "pthreadVCE3.lib")
#pragma comment(lib, "pthreadVSE3.lib")
#pragma comment(lib, "rsvg-2.lib")
#pragma comment(lib, "tiff.lib")
#pragma comment(lib, "turbojpeg.lib")
#pragma comment(lib, "zlib.lib")
